services:
  backend:
      build: ./simple-api-student-main
      container_name: my-simpleapi
      networks: 
        - app-network
      depends_on:
        - database

  database:
      build: ./database
      container_name: my-postgres
      networks:
        - app-network

  httpd:
      build: ./http-server
      container_name: my-httpd
      ports:
        - "8082:80"
      networks: 
        - app-network
      depends_on:
        - backend

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local