- hosts: all
  gather_facts: true
  become: true

  vars:
    ansible_python_interpreter: /usr/bin/python3
    app_network: my_app_network

  roles:
    - docker
    - network
    - database
    - app
    # - frontend
    - proxy